package teclient

import (
	"net/http"
	"sync"
)

// APIEnvironment.
type APIEnvironment int

const (
	ProdEnv    APIEnvironment = 0
	StagingEnv APIEnvironment = 1
)

// APIMessage.
type APIMessage struct {
	Message string `json:"message"`
}

type APIDetail struct {
	Detail string `json:"detail"`
}

type TokenStruct struct {
	Token     string `json:"access_token"`
	ExpiresIn int    `json:"expires_in"`
	TokenType string `json:"token_type"`
	Scope     string `json:"scope"`
}

type Client struct {
	HTTPClient *http.Client
	Token      TokenStruct

	HostURL         string
	CompanyID       int
	ClientID        string
	ClientSecret    string
	VerifySSL       bool
	UserAgent       string
	ProviderVersion string

	// cache of GetTranscodingAllowedValues, see its comment
	allowedValuesMu sync.Mutex
	allowedValues   *TranscodingAllowedValuesAPIModel
}

// SiteAPIModel.
type SiteAPIModel struct {
	ID      int    `json:"id"`
	Company int    `json:"company"`
	URL     string `json:"url"`
	Active  bool   `json:"active"`
	Ssl     bool   `json:"ssl"`
}

type SiteNewAPIModel struct {
	URL string `json:"url"`
}

type SiteVerifyStringAPIModelRequest struct {
	Domain string `json:"domain"`
}

type SiteVerifyStringAPIModelResponse struct {
	Txt string `json:"txt"`
}

// BackendAPIModel.
type BackendAPIModel struct {
	ID           int    `json:"id"`
	Company      int    `json:"company"`
	Name         string `json:"name"`
	Origin       string `json:"origin"`
	Ssl          bool   `json:"ssl"`
	Port         int    `json:"port"`
	Headers      string `json:"extra_headers"`
	HCHost       string `json:"host"`
	HCPath       string `json:"health_check"`
	HCStatusCode int    `json:"status_code"`
	HCInterval   int    `json:"interval"`
	HCDisabled   bool   `json:"no_probe"`
}

type NewBackendAPIModel struct {
	Name         string `json:"name"`
	Origin       string `json:"origin"`
	Ssl          bool   `json:"ssl"`
	Port         int    `json:"port"`
	Headers      string `json:"extra_headers"`
	HCHost       string `json:"host"`
	HCPath       string `json:"health_check"`
	HCStatusCode int    `json:"status_code"`
	HCInterval   int    `json:"interval"`
	HCDisabled   bool   `json:"no_probe"`
}

// VCLConfCreator.
type VCLConfCreator struct {
	ID        int    `json:"id"`
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Username  string `json:"username"`
}

type VCLConfAPIModel struct {
	ID             int            `json:"id"`
	Company        int            `json:"company"`
	VCLCode        string         `json:"config_body"`
	UploadDate     string         `json:"upload_dt"`
	ProductionDate string         `json:"production_dt"`
	Validated      bool           `json:"validated"`
	Active         bool           `json:"active"`
	Deployed       bool           `json:"deployed"`
	CreatorUser    VCLConfCreator `json:"creator_user"`
	Comment        string         `json:"comment"`
}

type NewVCLConfAPIModel struct {
	VCLCode string `json:"config_body"`
	Comment string `json:"comment"`
}

// SSLCertificate.
type SSLCertificate struct {
	ID            int      `json:"id"`
	Company       int      `json:"company"`
	CommonName    string   `json:"name"`
	Domains       []string `json:"domains"`
	Expiration    string   `json:"expiration"`
	Autogenerated bool     `json:"autogenerated"`
	Standalone    bool     `json:"standalone"`
	DNSChallenge  bool     `json:"dns_challenge"`
	PublicKey     string   `json:"cert"`
	PrivateKey    string   `json:"key"`
}

type SSLCustomCertificate struct {
	ID            int    `json:"id"`
	Autogenerated bool   `json:"autogenerated"`
	DNSChallenge  bool   `json:"dns_challenge"`
	PublicKey     string `json:"cert"`
	PrivateKey    string `json:"key"`
}

// CRDNSKeys for DNS Certificate Requests.
type CRDNSKeys struct {
	KeyNameID int    `json:"key_name_id"`
	KeyName   string `json:"key_name"`
}

type CRDNSProvider struct {
	ID       int         `json:"id"`
	HookName string      `json:"hook_name"`
	Provider string      `json:"provider"`
	Keys     []CRDNSKeys `json:"keys"`
}

type CRDNSCNAMEVerification struct {
	CNAME string `json:"cname"`
}

type CRDNSCreds struct {
	Provider string `json:"provider"`
	KeyName  string `json:"dns_key_name"`
	KeyValue string `json:"dns_key_value"`
}

type CRDNSCredential struct {
	ID    int          `json:"id"`
	Alias string       `json:"alias"`
	Creds []CRDNSCreds `json:"creds"`
}

type NewCRDNSCreds struct {
	KeyName  string `json:"hook_key_name"`
	KeyValue string `json:"hook_key_value"`
}

type NewCRDNSCredential struct {
	Alias string          `json:"alias"`
	Creds []NewCRDNSCreds `json:"creds"`
}

type CertReqDNS struct {
	ID         int    `json:"id"`
	Credential int    `json:"credential"`
	Domains    string `json:"domains"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
	// as pointers since they can be null
	CertificateID *int    `json:"certificate"`
	Log           *string `json:"log"`
}

// CertReqHTTP (HTTP Certificate Request).
type CertReqHTTP struct {
	ID         int    `json:"id"`
	CommonName string `json:"cn"`
	SAN        string `json:"san"`
	Standalone bool   `json:"standalone"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"last_modified_at"`
	// as pointers since they can be null
	CertificateID *int    `json:"certificate"`
	Log           *string `json:"error_text"`
}

// TranscodingProfileAPIModel is the transcoding profile as returned by every endpoint,
// custom_profiles included (the spec documents the POST response without them, but the
// API returns them).
type TranscodingProfileAPIModel struct {
	ID              int    `json:"id"`
	Company         int    `json:"company"`
	Name            string `json:"name"`
	VideoFormat     string `json:"video_format"`
	VideoCodec      string `json:"video_codec"`
	VideoBitrate    int    `json:"video_bitrate"`
	AudioBitrate    int    `json:"audio_bitrate"`
	RestrictBitrate bool   `json:"restrict_bitrate"`
	// as pointers since they can be null
	VideoWidth  *int    `json:"video_width"`
	VideoHeight *int    `json:"video_height"`
	VideoAspect *string `json:"video_aspect"`
	AudioCodec  *string `json:"audio_codec"`

	CustomProfiles []CustomProfileAPIModel `json:"custom_profiles"`
}

// NewTranscodingProfileAPIModel is the create/update payload for a transcoding profile.
// CustomProfiles is always sent: when omitted the API leaves the custom profiles untouched,
// when present it replaces the full list (types present are upserted, absent are deleted).
type NewTranscodingProfileAPIModel struct {
	Name            string `json:"name"`
	VideoFormat     string `json:"video_format"`
	VideoCodec      string `json:"video_codec"`
	VideoBitrate    int    `json:"video_bitrate"`
	AudioBitrate    int    `json:"audio_bitrate"`
	RestrictBitrate bool   `json:"restrict_bitrate"`

	// as pointers since they can be null
	VideoWidth  *int    `json:"video_width"`
	VideoHeight *int    `json:"video_height"`
	VideoAspect *string `json:"video_aspect"`
	AudioCodec  *string `json:"audio_codec"`

	// OverlayProfileAPIModel or HLSProfileAPIModel
	CustomProfiles []any `json:"custom_profiles"`
}

// OverlayProfileAPIModel is the "overlay" element of the custom_profiles payload. Optional
// fields are sent without omitempty: the upsert keeps the previous value of an absent
// field, so an explicit null is the only way to clear it.
type OverlayProfileAPIModel struct {
	ProfileType string `json:"profile_type"`
	Position    string `json:"position"`

	// as pointers since they can be null
	URL         *string  `json:"url"`
	ScaleWidth  *int     `json:"scale_width"`
	ScaleHeight *int     `json:"scale_height"`
	Opacity     *float64 `json:"opacity"`
	Horizontal  *string  `json:"horizontal"`
	Vertical    *string  `json:"vertical"`
	OffsetX     *int     `json:"offset_x"`
	OffsetY     *int     `json:"offset_y"`
}

// HLSProfileAPIModel is the "hls" element of the custom_profiles payload. Unlike overlay it
// has no position: the API does not store it for hls (it is neither returned nor required).
type HLSProfileAPIModel struct {
	ProfileType string `json:"profile_type"`

	// as pointers since they can be null
	HLSTime      *int    `json:"hls_time"`
	HLSListSize  *int    `json:"hls_list_size"`
	MasterPlName *string `json:"master_pl_name"`
	HLSFlags     *string `json:"hls_flags"`
	PixFmt       *string `json:"pix_fmt"`
	Framerate    *int    `json:"framerate"`
	H264Preset   *string `json:"h264_preset"`
	H264Profile  *string `json:"h264_profile"`
	H264Level    *string `json:"h264_level"`
	Maxrate      *string `json:"maxrate"`
	Bufsize      *string `json:"bufsize"`
	BStrategy    *int    `json:"b_strategy"`
	Refs         *int    `json:"refs"`
	Coder        *int    `json:"coder"`
	ScThreshold  *int    `json:"sc_threshold"`
}

// CustomProfileAPIModel decodes a custom profile returned by the API: it is the union of the
// overlay and hls fields, and only one of the two sets is populated, depending on
// ProfileType. It is response-only, see OverlayProfileAPIModel and HLSProfileAPIModel for
// the payload. The "transcoding_profile" field returned by the API is intentionally not modeled:
// these routes are not decoded with DisallowUnknownFields.
type CustomProfileAPIModel struct {
	ProfileType string `json:"profile_type"`
	Position    string `json:"position"`

	// overlay fields, as pointers since they can be null
	URL         *string  `json:"url"`
	ScaleWidth  *int     `json:"scale_width"`
	ScaleHeight *int     `json:"scale_height"`
	Opacity     *float64 `json:"opacity"`
	Horizontal  *string  `json:"horizontal"`
	Vertical    *string  `json:"vertical"`
	OffsetX     *int     `json:"offset_x"`
	OffsetY     *int     `json:"offset_y"`

	// hls fields, as pointers since they can be null
	HLSTime      *int    `json:"hls_time"`
	HLSListSize  *int    `json:"hls_list_size"`
	MasterPlName *string `json:"master_pl_name"`
	HLSFlags     *string `json:"hls_flags"`
	PixFmt       *string `json:"pix_fmt"`
	Framerate    *int    `json:"framerate"`
	H264Preset   *string `json:"h264_preset"`
	H264Profile  *string `json:"h264_profile"`
	H264Level    *string `json:"h264_level"`
	Maxrate      *string `json:"maxrate"`
	Bufsize      *string `json:"bufsize"`
	BStrategy    *int    `json:"b_strategy"`
	Refs         *int    `json:"refs"`
	Coder        *int    `json:"coder"`
	ScThreshold  *int    `json:"sc_threshold"`
}

// TranscodingAllowedValuesAPIModel lists the values accepted by the transcoding profile enums.
type TranscodingAllowedValuesAPIModel struct {
	VideoFormats []string `json:"video_formats"`
	VideoCodecs  []string `json:"video_codecs"`
	AudioCodecs  []string `json:"audio_codecs"`
	AspectRatio  []string `json:"aspect_ratio"`
}
